spring:
  application:
    name: schedule-parser
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=200,expireAfterWrite=60m   # кэш живёт 1 час

server:
  port: 8080

database:
  csv-filename: schedule.csv

google:
  sheets:
    api-key: AIzaSyBtXCAztc16UFYGK0VVKmL9qLX2qz5WnrY
    spreadsheet-id: 13CqvyFsOa5Z5LYCfMCz4IyAnuTIcjYqI0ARgt8-5MpQ  # ID таблицы из URL
    data-range: B2:BF44

schedule:
  cache:
    refresh-cron: "0 0 * * * *"         # сброс кэша каждый час

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    com.example.scheduleparser: DEBUG
